production:
  auto_deploy_on: refs/heads/master
  production_environment: true
  required_contexts: ["test"]
  environment: production

review:
  # Set the transient environment flag to let GitHub and Deliverybot know that
  # this environment should be destroyed when the PR is closed.
  transient_environment: true
  production_environment: true

  # Dynamic environment name. The environment will look like pr123.
  environment: production
  required_contexts: ["test"]