name: Deploy

on: ['deployment']

jobs:

  deployment:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'deployment pending'
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'pending'
          token: '${{ github.token }}'

      - name: deploy
        run: |
          echo "environment - ${{ github.event.deployment.task }}"
          echo "payload - ${{ github.event.deployment.payload }}"

      - uses: actions/checkout@v1

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: niecore/functional-reactive-smarthome
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Deploy ${{ github.event.deployment.environment }} - ${{ github.event.deployment.ref }}'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SWARM_SSH_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          passphrase: ${{ secrets.DOCKER_PASSPHRASE }}
          port: ${{ secrets.DOCKER_SWARM_PORT }}
          key: ${{ secrets.DOCKER_SWARM_PRIVATE_KEY}}
          script: docker service update --image niecore/functional-reactive-smarthome:${{ github.event.deployment.ref }} functional-reactive-smarthome

      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'failure'
          token: '${{ github.token }}'
