name: Push to Docker Hub

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: niecore/functional-reactive-smarthome
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy to docker swarm
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SWARM_SSH_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          passphrase: ${{ secrets.DOCKER_PASSPHRASE }}
          port: ${{ secrets.DOCKER_SWARM_PORT }}
          key: ${{ secrets.DOCKER_SWARM_PRIVATE_KEY}}
          script: docker service update --image niecore/functional-reactive-smarthome:latest functional-reactive-smarthome