name: functional-reactive-smarthome workflow

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci
          npm test
        env:
          CI: true

  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: niecore/functional-reactive-smarthome
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy to docker swarm
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOCKER_SWARM_SSH_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          passphrase: ${{ secrets.DOCKER_PASSPHRASE }}
          port: ${{ secrets.DOCKER_SWARM_PORT }}
          key: ${{ secrets.DOCKER_SWARM_PRIVATE_KEY}}
          script: docker service update --image niecore/functional-reactive-smarthome:latest functional-reactive-smarthome